In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,2,5]])
print("Array is of type : ", type(arr))
print("No. of dimentiond : ", arr.ndim)
print("Shape of array : ", arr.shape)
print("Size of araay : ", arr.size)
print("Array stores elements of type : ", arr.dtype)

Array is of type :  <class 'numpy.ndarray'>
No. of dimentiond :  2
Shape of array :  (2, 3)
Size of araay :  6
Array stores elements of type :  int64


In [ ]:
a = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print("A is ",a)
b = np.array([1,3,2])
print("B is ",b)
c = np.zeros((3,4))
print("C is ",c)


A is  [[1. 2. 3.]
 [4. 5. 6.]]
B is  [1 3 2]
C is  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d = np.random.randint(10,20,10)

In [ ]:
print(d)

[18 13 10 12 16 16 14 11 15 12]


In [ ]:
e = np.random.randint(10,20,15)
print(e)

[15 11 18 19 12 14 14 15 17 11 18 11 15 16 12]


In [ ]:
f = np.array([1,3,2])
print(f*5)

[ 5 15 10]


In [ ]:
print(d*5)

[90 65 50 60 80 80 70 55 75 60]
